server:
  port: 8080

spring:
  config:
    activate:
      on-profile: local

  application:
    name: spotify-reactive-api
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/spotifyapi
    username: postgres
    password: postgres
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/spotifyapi
    user: postgres
    password: postgres

spotify:
  data:
    file-path: ./src/main/resources/900k Definitive Spotify Dataset.json

logging:
  level:
    org.springframework.r2dbc: DEBUG
    io.r2dbc.postgresql: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
  show-actuator: true

