server:
  port: 8080

spring:
  config:
    activate:
      on-profile: docker

  application:
    name: spotify-reactive-api
  r2dbc:
    url: r2dbc:postgresql://postgres:5432/spotifyapi
    username: postgres
    password: postgres
  flyway:
    enabled: true
    url: jdbc:postgresql://postgres:5432/spotifyapi
    user: postgres
    password: postgres

spotify:
  data:
    file-path: /app/resources/data/900k Definitive Spotify Dataset.json

logging:
  level:
    org.springframework.r2dbc: INFO
    io.r2dbc.postgresql: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    validator-url: none
  show-actuator: true

