server:
  port: 8080

spring:
  application:
    name: spotify-reactive-api
  r2dbc:
    url: ${SPRING_R2DBC_URL}
    username: ${SPRING_R2DBC_USERNAME}
    password: ${SPRING_R2DBC_PASSWORD}
  flyway:
    enabled: true
    url: ${SPRING_FLYWAY_URL}
    user: ${SPRING_FLYWAY_USERNAME}
    password: ${SPRING_FLYWAY_PASSWORD}

logging:
  level:
    org.springframework.r2dbc: INFO
    io.r2dbc.postgresql: INFO

