server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: spotify-reactive-api
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://postgres:5432/spotifyapi}
    username: ${SPRING_R2DBC_USERNAME:postgres}
    password: ${SPRING_R2DBC_PASSWORD:postgres}

logging:
  level:
    org.springframework.r2dbc: INFO
    io.r2dbc.postgresql: INFO

